services:
  - type: web
    name: papersetu
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python manage.py migrate --no-input && daphne -b 0.0.0.0 -p $PORT conference_mgmt.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: conference_mgmt.settings
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: papersetu2.onrender.com,*.onrender.com 