# Generated by Django 5.2.3 on 2025-06-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conference',
            name='paper_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='conference',
            name='paper_submission_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
