# Generated by Django 5.2.3 on 2025-06-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_conference_domain_conference_paper_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='decision',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=10, null=True),
        ),
    ]
