# Generated by Django 5.2.3 on 2025-07-04 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='acronym',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='conference',
            name='area_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conference',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='conference',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conference',
            name='estimated_submissions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conference',
            name='organizer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conference',
            name='organizer_web_page',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='other_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='primary_area',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('DS', 'Data Science'), ('CV', 'Computer Vision'), ('NLP', 'Natural Language Processing'), ('SE', 'Software Engineering'), ('CN', 'Computer Networks'), ('SEC', 'Cyber Security'), ('HCI', 'Human-Computer Interaction'), ('DB', 'Databases'), ('IOT', 'Internet of Things'), ('BIO', 'Bioinformatics'), ('EDU', 'Education Technology'), ('GRAPH', 'Computer Graphics'), ('OTHER', 'Other')], default='AI', max_length=50),
        ),
        migrations.AddField(
            model_name='conference',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_conferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conference',
            name='secondary_area',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('DS', 'Data Science'), ('CV', 'Computer Vision'), ('NLP', 'Natural Language Processing'), ('SE', 'Software Engineering'), ('CN', 'Computer Networks'), ('SEC', 'Cyber Security'), ('HCI', 'Human-Computer Interaction'), ('DB', 'Databases'), ('IOT', 'Internet of Things'), ('BIO', 'Bioinformatics'), ('EDU', 'Education Technology'), ('GRAPH', 'Computer Graphics'), ('OTHER', 'Other')], default='AI', max_length=50),
        ),
        migrations.AddField(
            model_name='conference',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conference',
            name='web_page',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
