# Generated by Django 5.2.3 on 2025-07-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_conference_acronym_conference_area_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='other_info',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='registration_fee',
        ),
    ]
