# Generated by Django 5.2.3 on 2025-07-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_remove_conference_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconferencerole',
            name='role',
            field=models.CharField(choices=[('chair', 'Chair'), ('author', 'Author'), ('reviewer', 'Reviewer'), ('pc_member', 'PC Member')], max_length=15),
        ),
    ]
