# Generated by Django 5.2.3 on 2025-07-07 07:09

from django.db import migrations
import secrets

def fill_tokens(apps, schema_editor):
    PCInvite = apps.get_model('conference', 'PCInvite')
    for invite in PCInvite.objects.all():
        if not invite.token:
            invite.token = secrets.token_urlsafe(32)
            invite.save()

class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_pcinvite'),
    ]

    operations = [
        migrations.RunPython(fill_tokens, reverse_code=migrations.RunPython.noop),
    ]
