# Generated by Django 5.2.3 on 2025-07-07 07:15

from django.db import migrations, models
import secrets

def add_name_token(apps, schema_editor):
    PCInvite = apps.get_model('conference', 'PCInvite')
    for invite in PCInvite.objects.all():
        if not hasattr(invite, 'name') or invite.name is None:
            invite.name = ''
        if not hasattr(invite, 'token') or not invite.token:
            invite.token = secrets.token_urlsafe(32)
        invite.save()

class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_pcinvite_token_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcinvite',
            name='name',
            field=models.CharField(max_length=255, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pcinvite',
            name='token',
            field=models.CharField(max_length=64, unique=True, default=secrets.token_urlsafe),
        ),
        migrations.RunPython(add_name_token, reverse_code=migrations.RunPython.noop),
    ]
