# Generated by Django 5.2.4 on 2025-07-07 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_pcinvite_add_name_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcinvite',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pcinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='pcinvite',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='ConferenceAdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configure_enabled', models.BooleanField(default=True)),
                ('workflow_enabled', models.BooleanField(default=False)),
                ('registration_enabled', models.BooleanField(default=False)),
                ('other_utilities_enabled', models.BooleanField(default=False)),
                ('analytics_enabled', models.BooleanField(default=False)),
                ('statistics_enabled', models.BooleanField(default=True)),
                ('demo_version_enabled', models.BooleanField(default=False)),
                ('tracks_enabled', models.BooleanField(default=False)),
                ('create_cfp_enabled', models.BooleanField(default=False)),
                ('create_program_enabled', models.BooleanField(default=False)),
                ('create_proceedings_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_settings', to=settings.AUTH_USER_MODEL)),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_settings', to='conference.conference')),
            ],
            options={
                'verbose_name': 'Conference Admin Settings',
                'verbose_name_plural': 'Conference Admin Settings',
                'unique_together': {('conference', 'chair')},
            },
        ),
    ]
