# Generated by Django 5.2.4 on 2025-07-07 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_conference_abstract_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(help_text='Individual or organization name', max_length=255)),
                ('country_region', models.CharField(help_text='Country or region', max_length=100)),
                ('registration_start_date', models.DateField(help_text='When registration opens')),
                ('estimated_attendees', models.IntegerField(help_text='Expected number of attendees')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or requirements')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for review')),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_application', to='conference.conference')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration Application',
                'verbose_name_plural': 'Registration Applications',
            },
        ),
    ]
