# Generated by Django 5.2.4 on 2025-07-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_registrationapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_final_list',
            field=models.BooleanField(default=False, help_text='Mark if this paper is included in the final endorsed list'),
        ),
    ]
