# Generated by Django 5.2.3 on 2025-07-08 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0014_paper_is_final_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconferencerole',
            name='role',
            field=models.CharField(choices=[('chair', 'Chair'), ('author', 'Author'), ('reviewer', 'Reviewer'), ('pc_member', 'PC Member'), ('subreviewer', 'Subreviewer')], max_length=15),
        ),
        migrations.CreateModel(
            name='SubreviewerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='invited', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreviewer_invited_by', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreviewer_invites', to='conference.paper')),
                ('subreviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreviewer_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
