# Generated by Django 5.2.3 on 2025-07-11 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_review_comments_review_confidence_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AlterField(
            model_name='conference',
            name='abstract_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='allow_supplementary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conference',
            name='blind_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='confidence_scores_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='max_paper_length',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='conference',
            name='multiple_authors_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='review_form_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='reviewers_per_paper',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country_region', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=255)),
                ('web_page', models.URLField(blank=True)),
                ('is_corresponding', models.BooleanField(default=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='conference.paper')),
            ],
        ),
    ]
