# Generated by Django 5.2.4 on 2025-07-13 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0017_paper_keywords_alter_conference_abstract_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceFeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('config', 'Config'), ('registration', 'Registration'), ('utilities', 'Other Utilities'), ('analytics', 'Analytics'), ('statistics', 'Statistics'), ('demo', 'Demo Version'), ('tracks', 'Tracks'), ('cfp', 'Create CFP'), ('program', 'Create Program'), ('proceedings', 'Create Proceedings')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_toggles', to='conference.conference')),
            ],
            options={
                'verbose_name': 'Conference Feature Toggle',
                'verbose_name_plural': 'Conference Feature Toggles',
                'unique_together': {('conference', 'feature')},
            },
        ),
    ]
