# Generated by Django 5.2.3 on 2025-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0018_conferencefeaturetoggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='payment_amount',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='paper',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
