# Generated by Django 5.2.3 on 2025-07-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0020_alter_paper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject')], help_text='Subreviewer recommendation (not final decision)', max_length=10, null=True),
        ),
    ]
