# Generated by Django 5.2.3 on 2025-07-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0021_review_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_id',
            field=models.CharField(blank=True, help_text='Unique Paper ID for search/reference', max_length=20, null=True, unique=True),
        ),
    ]
