# Generated by Django 5.2.4 on 2025-07-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0022_paper_paper_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='plagiarism_percentage',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Plagiarism percentage (0-100)', null=True),
        ),
    ]
