# Generated by Django 5.2.4 on 2025-07-24 18:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0023_paper_plagiarism_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subreviewerinvite',
            unique_together={('paper', 'subreviewer')},
        ),
    ]
