# Generated by Django 5.2.4 on 2025-07-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0024_alter_subreviewerinvite_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subreviewerinvite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conference',
            name='chair_email',
            field=models.EmailField(blank=True, help_text="Conference chair's email address", max_length=254),
        ),
        migrations.AddField(
            model_name='conference',
            name='chair_name',
            field=models.CharField(blank=True, help_text="Conference chair's full name", max_length=255),
        ),
    ]
