# Generated by Django 5.2.3 on 2025-07-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0028_add_track_to_subreviewerinvite'),
        ('conference', '0028_alter_track_id'),
    ]

    operations = [
    ]
