# Generated by Django 5.2.3 on 2025-07-27 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0030_alter_track_chair'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconferencerole',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_roles', to='conference.track'),
        ),
    ]
