# Generated by Django 5.2.4 on 2025-07-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0031_userconferencerole_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Main contact email for registration', max_length=254),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('bank', 'Bank Transfer'), ('onsite', 'Onsite'), ('other', 'Other')], default='online', help_text='Preferred payment method', max_length=20),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='registration_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('student', 'Student'), ('invited', 'Invited'), ('other', 'Other')], default='regular', help_text='Type of registration', max_length=20),
        ),
    ]
