# Generated by Django 5.2.3 on 2026-07-30 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0032_registrationapplication_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile (WhatsApp) No.')),
                ('num_authors', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('other', 'Other')], max_length=10)),
                ('num_authors_other', models.CharField(blank=True, max_length=10)),
                ('name_first_author', models.CharField(max_length=255, verbose_name='Name of 1st Author')),
                ('affiliation_first_author', models.CharField(max_length=255, verbose_name='Affiliation of 1st Author')),
                ('designation_first_author', models.CharField(choices=[('professor', 'Professor/Assoc Prof/Asst Professor'), ('industry', 'Industry Expert'), ('researcher', 'Researcher/PhD Scholar'), ('pg', 'PG Student'), ('ug', 'UG Student')], max_length=20, verbose_name='Designation of 1st Author')),
                ('affiliation_corresponding', models.CharField(max_length=255, verbose_name='Affiliation of Corresponding Author')),
                ('has_international_author', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Any International Author?')),
                ('affiliation_international', models.CharField(blank=True, max_length=255, verbose_name='Affiliation of International Author (if any)')),
                ('presentation_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'PIET, Jaipur - Offline (Mandatory for Local Participants)')], max_length=20)),
                ('publication_choice', models.CharField(choices=[('acm', 'ACM-ICPS (Scopus Conference Proceedings, Open Access)'), ('taru', 'Taru-JDMSC (Scopus Q1, Journal, Additional APC Applicable)')], max_length=10)),
                ('amount_paid', models.CharField(max_length=50, verbose_name='Amount Paid for Registration (INR/USD)')),
                ('has_membership', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='IEEE/ACM/FIP/CSI/IETE Membership?')),
                ('membership_proof', models.FileField(blank=True, null=True, upload_to='registration/membership/', verbose_name='Membership Proof')),
                ('revised_paper', models.FileField(upload_to='registration/revised_papers/', verbose_name='Word/Latex Revised Paper')),
                ('pdf_copy', models.FileField(blank=True, null=True, upload_to='registration/pdf_copies/', verbose_name='PDF Copy')),
                ('plagiarism_report', models.FileField(blank=True, null=True, upload_to='registration/plagiarism/', verbose_name='Plagiarism Report')),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='conference.paper')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
