# Generated by Django 5.2.3 on 2026-07-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0033_conferenceregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceregistration',
            name='revised_paper',
            field=models.FileField(blank=True, null=True, upload_to='registration/revised_papers/', verbose_name='Word/Latex Revised Paper'),
        ),
    ]
